# Site settings
title: NatureSpheres
description: > # this means to ignore newlines until "baseurl:"
Capturing the nature.
baseurl: "/example" # the subpath of your site, e.g. /blog/
url: "http://64kilobit.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
